import './styles.css';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
const $ = (s,root=document)=>root.querySelector(s);
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];
const dialog = $('#experience');
const content = $('#dialog-content');
const prompt = $('#skin-prompt');
const fileInput = $('#photo');
let photoURL = null, pendingTimer = null, returnFocus = null;
let state = {context:'', time:'Poucos passos', budget:'Até R$ 150', checkin:''};
const escape = (text)=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name=>`<i class="ph ph-${name}" aria-hidden="true"></i>`;
function openDialog(html){clearTimeout(pendingTimer);content.innerHTML=html;if(!dialog.open){returnFocus=document.activeElement;dialog.showModal();}dialog.scrollTop=0;requestAnimationFrame(()=>{const el=$('#dialog-title',content);if(el){el.tabIndex=-1;el.focus({preventScroll:true});}});}
function closeDialog(){clearTimeout(pendingTimer);dialog.close();returnFocus?.focus({preventScroll:true});}
$('#close-dialog').addEventListener('click',closeDialog);
dialog.addEventListener('cancel',()=>clearTimeout(pendingTimer));
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
const notice = '<p class="dialog-notice">Demonstração interativa. Nenhuma avaliação de pele ou recomendação real está sendo feita.</p>';
function startAnalysis(example=false){state.context=example?'Quero começar com poucos passos e entender o que faz parte da minha rotina.':prompt.value.trim();showContext();}
function showContext(){openDialog(`<p class="eyebrow">SUA ROTINA / 01 DE 02</p><h2 id="dialog-title">O cuidado começa<br>pelo seu contexto.</h2>${notice}<form id="context-form"><label for="context-input">O que você gostaria de cuidar?</label><textarea id="context-input" maxlength="800" required>${escape(state.context)}</textarea><label for="time-select">Como você prefere começar?</label><select id="time-select"><option>Poucos passos</option><option>Quero ajustar o que já uso</option><option>Quero explorar possibilidades</option></select><label for="budget-select">Qual orçamento quer considerar?</label><select id="budget-select"><option>Até R$ 150</option><option>Até R$ 250</option><option>Prefiro decidir depois</option></select><p style="font-size:11px;margin-top:15px">${photoURL?'Foto selecionada neste navegador. A demonstração não analisa a imagem.':'Você está seguindo sem foto. Tudo bem.'}</p><button type="submit" class="pill dark">Explorar minha rotina ${icon('arrow-up-right')}</button></form>`);$('#time-select').value=state.time;$('#budget-select').value=state.budget;$('#context-form').addEventListener('submit',e=>{e.preventDefault();const next=$('#context-input').value.trim();if(!next){$('#context-input').setCustomValidity('Conte um pouco sobre o que você procura.');$('#context-input').reportValidity();return;}state.context=next;state.time=$('#time-select').value;state.budget=$('#budget-select').value;openDialog(`<p class="eyebrow">DEMONSTRAÇÃO</p><h2 id="dialog-title">Organizando o exemplo.</h2><p>Seu contexto fica neste navegador.</p><div class="loading-dot" aria-hidden="true"></div><p role="status">Preparando a visualização da rotina demonstrativa…</p>`);pendingTimer=setTimeout(showResult,700);});$('#context-input').addEventListener('input',e=>e.target.setCustomValidity(''));}
function showResult(){const few=state.time==='Poucos passos';openDialog(`<p class="eyebrow">SUA ROTINA / 02 DE 02 · EXEMPLO</p><h2 id="dialog-title">${few?'O essencial para explorar.':'Uma rotina para entender.'}</h2><p>Uma prévia de como as escolhas seriam apresentadas.</p><div class="summary-quote">“${escape(state.context)}”</div><p style="font-size:12px">Sua preferência: <strong>${escape(state.time)}</strong><br>Orçamento informado: <strong>${escape(state.budget)}</strong></p><div class="result-row"><span>01</span><div><h3>Cleanse</h3><p>Limpeza · primeiro passo do catálogo conceitual.</p></div></div>${!few?'<div class="result-row"><span>02</span><div><h3>Balance</h3><p>Sérum · item complementar para conhecer, sem indicação clínica.</p></div></div>':''}<div class="result-row"><span>${few?'02':'03'}</span><div><h3>Comfort</h3><p>Hidratação · completa a apresentação de uma rotina ${few?'curta':'demonstrativa'}.</p></div></div><p class="dialog-notice">A preferência muda a apresentação deste exemplo. Não há IA, análise da foto ou validação de adequação. Preços, fórmulas e instruções ainda não foram definidos; o orçamento não é uma cotação.</p><div class="actions"><button class="pill outline" id="edit-context">Editar contexto</button><button class="pill dark" id="show-checkin">Conhecer o check-in ${icon('arrow-up-right')}</button></div>`);$('#edit-context').onclick=showContext;$('#show-checkin').onclick=showCheckin;}
function showCheckin(){openDialog(`<p class="eyebrow">ACOMPANHAMENTO / DEMONSTRAÇÃO</p><h2 id="dialog-title">Como foi cuidar<br>de você hoje?</h2><p>O próximo passo também pode ser simplificar.</p><div class="choices" role="group" aria-label="Sua experiência"><button class="choice" aria-pressed="false">Consegui manter</button><button class="choice" aria-pressed="false">Preciso ajustar</button><button class="choice" aria-pressed="false">Ainda não comecei</button></div><label for="checkin-note">Quer contar algo mais? <span style="color:#7b8773">Opcional</span></label><textarea id="checkin-note" placeholder="O que funcionou? O que ficou difícil?" maxlength="600"></textarea><p id="checkin-error" role="alert" hidden>Escolha uma das opções para continuar.</p><button id="save-checkin" class="pill dark">Concluir check-in ${icon('check')}</button><p style="font-size:11px;margin-top:20px">Exemplo local. Sem conta, envio de dados ou histórico salvo.</p>`);let selected='';$$('.choice',content).forEach(el=>el.onclick=()=>{selected=el.textContent;$$('.choice',content).forEach(b=>b.setAttribute('aria-pressed',String(b===el)));$('#checkin-error').hidden=true;});$('#save-checkin').onclick=()=>{if(!selected){$('#checkin-error').hidden=false;return;}state.checkin=selected;openDialog(`<p class="eyebrow">CHECK-IN CONCLUÍDO / DEMONSTRAÇÃO</p><h2 id="dialog-title">Um passo de cada vez.</h2><p>Você marcou: <strong>${escape(selected)}</strong>.</p><p class="dialog-notice">Assim termina o exemplo de acompanhamento. Nada foi enviado ou salvo em uma conta.</p><button id="checkin-close" class="pill dark">Voltar à página ${icon('arrow-up-right')}</button>`);$('#checkin-close').onclick=closeDialog;};}
$('#prompt-form').addEventListener('submit',e=>{e.preventDefault();if(!prompt.value.trim()){const error=$('#prompt-error');error.textContent='Conte um pouco sobre sua pele ou escolha uma sugestão para começar.';error.hidden=false;prompt.focus();return;}$('#prompt-error').hidden=true;startAnalysis();});
prompt.addEventListener('input',()=>$('#prompt-error').hidden=true);
$$('[data-prompt]').forEach(el=>el.onclick=()=>{prompt.value=el.dataset.prompt;$('#prompt-error').hidden=true;prompt.focus({preventScroll:true});});
$$('.start').forEach(el=>el.onclick=()=>{if(dialog.open)closeDialog();$('#inicio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setTimeout(()=>prompt.focus({preventScroll:true}),300);});
$$('[data-demo]').forEach(el=>el.onclick=()=>startAnalysis(true));
$$('[data-checkin]').forEach(el=>el.onclick=showCheckin);
fileInput.addEventListener('change',()=>{const file=fileInput.files?.[0];if(!file)return;const error=$('#prompt-error');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){error.textContent='Escolha uma imagem JPG, PNG ou WebP de até 10 MB.';error.hidden=false;fileInput.value='';return;}if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(file);$('#attachment').hidden=false;$('#attachment span').textContent=file.name;error.hidden=true;});
$('#remove-photo').onclick=()=>{if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null;fileInput.value='';$('#attachment').hidden=true;};
const navToggle=$('.menu-toggle');navToggle.onclick=()=>{const isOpen=$('.nav nav').classList.toggle('open');navToggle.setAttribute('aria-expanded',String(isOpen));navToggle.setAttribute('aria-label',isOpen?'Fechar menu':'Abrir menu');};$$('.nav nav a').forEach(el=>el.onclick=()=>{$('.nav nav').classList.remove('open');navToggle.setAttribute('aria-expanded','false');navToggle.setAttribute('aria-label','Abrir menu');});
const steps=[['Vamos entender você.','“Quero uma rotina simples que caiba nas minhas manhãs.”','O que você já usa hoje?','Contexto antes da escolha'],['Cada escolha, explicada.','Sua preferência: começar com poucos passos.','Cleanse + Comfort · exemplo de rotina essencial','Você entende a função de cada item'],['A rotina acompanha você.','“Quero ajustar o cuidado ao meu novo horário.”','O que mudou desde a última vez?','Seu próximo passo pode ser simplificar']];
function selectStep(index){$$('[data-step]').forEach((el,i)=>{el.classList.toggle('active',i===index);el.setAttribute('aria-selected',String(i===index));el.tabIndex=i===index?0:-1;});$('#step-panel').setAttribute('aria-labelledby',`step-${index}`);$('#step-title').textContent=steps[index][0];$('#step-text').textContent=steps[index][1];$('#step-reply').textContent=steps[index][2];$('.card-foot span').textContent=steps[index][3];}
$$('[data-step]').forEach(el=>{el.onclick=()=>selectStep(+el.dataset.step);el.onkeydown=e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const current=+el.dataset.step;const index=e.key==='Home'?0:e.key==='End'?2:(current+(['ArrowRight','ArrowDown'].includes(e.key)?1:2))%3;selectStep(index);$(`#step-${index}`).focus();}};});
$('#compare-range').addEventListener('input',e=>$('.comparison').style.setProperty('--split',`${e.target.value}%`));
const stories=[['Quero começar com poucos passos e entender onde meu dinheiro está indo.','Lucas, 26','Começar sem complicar.'],['Quero entender se a indicação considera o que já uso e o que minha pele tolera.','Marina, 29','Confiança para fazer escolhas.'],['Quero cuidar da pele sem transformar minha rotina em uma obrigação difícil.','Denise, 48','Cuidado que cabe na vida.']];let storyIndex=0;function showStory(delta){storyIndex=(storyIndex+delta+stories.length)%stories.length;$('#story-quote').textContent=stories[storyIndex][0];$('#story-name').textContent=stories[storyIndex][1];$('#story-desc').textContent=stories[storyIndex][2];$('#story-count').textContent=`0${storyIndex+1} / 03`;}
$('#prev-story').onclick=()=>showStory(-1);$('#next-story').onclick=()=>showStory(1);
const products=[['Cleanse','Limpeza · 150 ml','O começo do ritual.'],['Balance','Sérum · 30 ml','Uma escolha com propósito.'],['Comfort','Hidratação · 50 ml','Seu momento de cuidado.']];
$$('[data-product]').forEach(el=>el.onclick=()=>{const p=products[+el.dataset.product];openDialog(`<p class="eyebrow">LINHA SKINBOOST / PRODUTO CONCEITUAL</p><h2 id="dialog-title">${p[0]}</h2><p>${p[1]}<br>${p[2]}</p><img src="/media/produtos-skinboost.png" alt="Família de embalagens conceituais SkinBoost" style="border-radius:13px;margin-top:24px"/><p class="dialog-notice">Conceito de embalagem. Fórmula, ingredientes, evidências, instruções e preço ainda não definidos. Produto indisponível para compra.</p><button class="pill dark" id="product-demo">Ver exemplo de rotina ${icon('arrow-up-right')}</button>`);$('#product-demo').onclick=()=>startAnalysis(true);});
const infos={privacy:['Sua foto. Sua escolha.','Neste protótipo, texto e foto ficam apenas na memória do navegador. Nada é enviado a uma IA ou armazenado em uma conta. Você pode remover a imagem pelo botão ao lado do nome do arquivo; ao recarregar a página, o estado da demonstração é descartado.'],trust:['Confiança, com clareza.','A proposta da SkinBoost é tornar consultáveis a origem, a composição e as evidências de cada produto, além dos limites da orientação. O projeto é fictício: ainda não existem produtos regularizados, certificados, estudos próprios ou uma IA avaliada. Essas informações precisam ser verificadas antes de qualquer operação real.'],about:['Uma experiência para explorar.','Este é um wireframe de alta fidelidade da SkinBoost. As interações demonstram a jornada; as imagens de pessoas e pele são representadas por espaços reservados. As embalagens são imagens conceituais, o frasco é uma cena 3D e as histórias representam personas fictícias. Não há diagnóstico, venda ou envio de dados.']};
$$('[data-info]').forEach(el=>el.onclick=()=>{const info=infos[el.dataset.info];openDialog(`<p class="eyebrow">SKINBOOST / PROJETO CONCEITUAL</p><h2 id="dialog-title">${info[0]}</h2><p>${info[1]}</p><button id="info-close" class="pill dark">Entendi ${icon('check')}</button>`);$('#info-close').onclick=closeDialog;});
const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.fromTo('.film-copy h2 span',{opacity:.38},{opacity:1,stagger:.25,ease:'none',scrollTrigger:{trigger:'.film-section',start:'top top',end:'bottom bottom',scrub:true}});ScrollTrigger.create({trigger:'.film-section',start:'top top',end:'bottom bottom',onUpdate:self=>{$('.film-track span').style.transform=`scaleX(${self.progress})`;}});});
window.addEventListener('load',()=>ScrollTrigger.refresh());document.fonts.ready.then(()=>ScrollTrigger.refresh());
const bottleObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){import('./bottle.js').then(m=>m.initBottle()).catch(()=>{$('#bottle-fallback').hidden=false;});bottleObserver.disconnect();}},{rootMargin:'800px'});bottleObserver.observe($('#produtos'));
window.addEventListener('pagehide',()=>{if(photoURL)URL.revokeObjectURL(photoURL);clearTimeout(pendingTimer);mm.revert();});
